### ISSUE TITLE
openai.error.AuthenticationError: <empty message>

### ISSUE THREAD

**Issue by Amar1701** [tomitokko/django-chatbot#3]
please give a proper solution and debug this one! thanks

C:\Users\AMARNATH.C\OneDrive\Documents\newChatbot\chatbotSRM> python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 21, 2023 - 13:16:47
Django version 4.2.2, using settings 'django_chatbot.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

[21/Jun/2023 13:16:57] "GET / HTTP/1.1" 200 4451
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\AMARNATH.C\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AMARNATH.C\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AMARNATH.C\OneDrive\Documents\newChatbot\chatbotSRM\chatbot\views.py", line 33, in chatbot
    response = ask_openai(message)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AMARNATH.C\OneDrive\Documents\newChatbot\chatbotSRM\chatbot\views.py", line 16, in ask_openai
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AMARNATH.C\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create       
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AMARNATH.C\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\AMARNATH.C\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AMARNATH.C\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\AMARNATH.C\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line    
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>

**Comment by Amar1701** [comment]
@tomitokko  please rectify above error
